name: discord-bot

services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    env_file:
      - .env # Provide BOT_TOKEN, CLIENT_ID, optional PORT
    ports:
      - "3000:${PORT-3000}"
    # If your environment blocks outbound connections, ensure egress is allowed to Discord gateway
